### ISSUE TITLE
Add cardio exercises

### ISSUE THREAD

**Issue by YeyoM** [YeyoM/wellness-mobile-app#145]
Grant the user the ability to add cardio exercises to their routines

**Comment by YeyoM** [comment]
That API does not include the tradmill

**Comment by Hofmann101** [comment]
Treadmill:

Calories Burned = (0.1 * Speed in km/h + 1.8 * Speed in km/h * Incline in %) * Weight in kg * Duration in minutes / 60

Stationary Bike:

Calories Burned = (7 * Resistance Level) * Weight in kg * Duration in minutes / 60

Elliptical Machine:

Calories Burned = (5 * Resistance Level) * Weight in kg * Duration in minutes / 60

Rowing Machine:

Calories Burned = (6 * Resistance Level) * Weight in kg * Duration in minutes / 60
