### ISSUE TITLE
Move lifts around Lift queue durning workout

### ISSUE THREAD

**Issue by Hofmann101** [YeyoM/wellness-mobile-app#153]
Currently lifts in the lift queue are fixed, users should be able to move around lifts in the lift queue in case they decide to change order of lifts during their routine

**Comment by YeyoM** [comment]
@Hofmann101 please specify the version of the app (last commit on your local computer) and if possible a video as evidence to be able to reproduce the issue

**Comment by YeyoM** [comment]
Uploading WhatsApp Video 2024-04-09 at 20.01.15 (1).mp4…
