### ISSUE TITLE
Duplicated lifts

### ISSUE THREAD

**Issue by Hofmann101** [YeyoM/wellness-mobile-app#155]
Currently the app allows you to add the same lift twice on the same day, a lift can be repeated for another day in the same routine but not twice in one day

**Comment by YeyoM** [comment]
@Hofmann101 please specify the version of the app (last commit on your local computer) and if possible a video as evidence to be able to reproduce the issue

**Comment by YeyoM** [comment]
On local for me it is working correctly...

https://github.com/YeyoM/wellness-mobile-app/assets/76639199/c4a8b836-233c-43c5-aee2-72a7b1b2ddee
