### ISSUE TITLE
No next lift button available

### ISSUE THREAD

**Issue by Hofmann101** [YeyoM/wellness-mobile-app#187]
routine/oEqsIZtEtZUEQ2jQpOPP
<img width="307" alt="image" src="https://github.com/YeyoM/wellness-mobile-app/assets/141708495/196fe1ec-5b20-437a-b1c6-06c25eef6e52">

**Comment by YeyoM** [comment]
![WhatsApp Image 2024-04-29 at 5 23 50 PM](https://github.com/YeyoM/wellness-mobile-app/assets/76639199/35763783-7459-4eef-a957-6ba2fd6a5b9b)

The same routine for me works perfect, maybe ask @Letalandroid also to check if for him it is working or not
